### ISSUE TITLE
ETHApp contract won't unlock entire amount

### ISSUE THREAD

**Issue by musnit** [Snowfork/polkadot-ethereum#121] opened 2020-10-07 17:28 UTC
@Noc2 got the following error the first time he ran the test suite. the second time it ran fine though. sounds like something fishy worth digging into - @denalimarsh @vgeddes any thoughts? maybe its a timing related thing.

```
sudo yarn test

yarn run v1.22.5
$ mocha --timeout 35000 --exit


  Bridge
    ETH App
      ✓ should transfer ETH from Ethereum to Substrate (10085ms)
      1) should transfer ETH from Substrate to Ethereum
    ERC20 App
      ✓ should transfer ERC20 tokens from Ethereum to Substrate (10174ms)
      ✓ should transfer ERC20 from Substrate to Ethereum (30078ms)


  3 passing (1m)
  1 failing

  1) Bridge
       ETH App
         should transfer ETH from Substrate to Ethereum:

      AssertionError: expected '0' to equal '10000000000000000'
      + expected - actual

      -0
      +10000000000000000
      
      at Context.<anonymous> (test/test.js:70:71)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)



error Command failed with exit code 1.

```

**Comment by musnit** [comment] 2020-10-07 18:04
From @vgeddes:
```
Its very likely a timing issue. I occasionally had the same errors.

We'll need to make the tests more robust by waiting for events before doing balance assertions
```

**Comment by vgeddes** [comment] 2020-10-11 21:34
Found the real issue, and its unrelated to timing. Its a problem with the EthApp solidity contract, because it refuses to unlock the entire locked amount of eth. For example if the contract is newly initialized the locked amount will be 0. Then suppose someone locks up 5 ETH. Then due to the erroneous constraint below, they can only ever have 4.999999999... unlocked.

https://github.com/Snowfork/polkadot-ethereum/blob/main/ethereum/contracts/ETHApp.sol#L64

**Comment by denalimarsh** [comment] 2020-10-12 15:26
Pushed a fix for this in https://github.com/Snowfork/polkadot-ethereum/pull/125. @vgeddes could you review and confirm that it fixes this issue?

**Comment by vgeddes** [comment] 2020-10-14 14:14
@denalimarsh confirmed that the issue is fixed:

```
vincent@oryx:~/code/polkadot-ethereum/test (main)$ yarn test
yarn run v1.22.4
$ mocha --timeout 35000 --exit


  Bridge
    ETH App
      ✓ should transfer ETH from Ethereum to Substrate (10097ms)
      ✓ should transfer ETH from Substrate to Ethereum (30095ms)
    ERC20 App
      ✓ should transfer ERC20 tokens from Ethereum to Substrate (10167ms)
      ✓ should transfer ERC20 from Substrate to Ethereum (30108ms)


  4 passing (1m)

Done in 81.64s.
```

**Closed by vgeddes** 2020-10-14 14:14 UTC
Labels: Component: Ethereum
